### ISSUE TITLE
gtx-date-time-picker cannot set width 100%

### ISSUE THREAD

**Issue by lucianbumb** [gentics/gentics-ui-core#5]
Hello guys, 

I want to make gtx-date-time-picker width responsive and I can't. 
Basically I have 8 input fields in 2 column grid layout and I want all of them to fill the cell width. 

Text and Select fields are working as expected, but the date-time-piker is not filling the width of the grid cell. 

How can I fix this small issue? 
Thak you!

PS: great job you did with this library, thanks for letting me use it.

**Comment by tommazzo89** [comment]
Hi,

Thank you for your interest in our library.
The issue you reported seems to be bug in the gtx-date-time-picker. We will take a look at how to fix this - of course you are welcome to make a pull request if you want.

Best regards

**Comment by tommazzo89** [comment]
The gtx-date-time-picker now (version 6.2.1) extends to the full width of the parent container.
